### ISSUE TITLE
Fix database schema

### ISSUE THREAD

**Issue by runceel** [ProjectBlueMonkey/BlueMonkey#10]
We should agreement to table column Expense and Report.

It is basis:
- Expense
  - CategoryId: int
  - Amount: number
  - Date: date
  - Receipt: string(picture image url)
  - Location: string
  - Note: string
  - ReportId: int
- Category
  - Name: string
- Report
  - Name: string
  - Date: date
  - Department: string( or int?)

All tables have Id: string, createdAt: date, updatedAt: date, version: binary.

**Comment by amay077** [comment]
Would you like add these?

* Expense
    * ExpenseId: int
    * SortOrder: int(for Report)

* Category
    * CategoryId: int

* Report
    * ReportId: int

**Comment by runceel** [comment]
Oh. Sorry! I missed.

- Expense
    - ReportId: ***string***
    - CategoryId: ***string***

Primary key column is add automatically from mobile apps.

I agree SortOrder column!!
Merged version:

- Expense
    - CategoryId: ***string***
    - Amount: number
    - Date: date
    - Receipt: string(picture image url)
    - Location: string
    - Note: string
    - ReportId: ***string***
    - ***SortOrder: int***

- Category
    - Name: string

- Report
    - Name: string
    - Date: date
    - Department: ***string(name or department table's id?)***

All tables have Id: string, createdAt: date, updatedAt: date, version: binary.

**Comment by amay077** [comment]
> All tables have Id: string, createdAt: date, updatedAt: date, version: binary.

Thanks for information.

One more thing,
We don't adopt "delete_flg pattern", right?

**Comment by nuitsjp** [comment]
I have some suggestions.

* I want to split the Location in latitude and longitude
* Additional SortOrder to Category
* Receipt want to split into separate table
* SortOrder of Expense table is necessary?

I tried writing ER diagram.

![bluemonkeyer](https://cloud.githubusercontent.com/assets/16175660/19559956/480bd98c-970d-11e6-83ed-07d2bba91bc4.jpg)

**Comment by nuitsjp** [comment]
Oh! I agree.
The figure also will fix tomorrow.

**Comment by amay077** [comment]
We also need ``User`` table what have ``UserName`` and twitter's ``SId``(and some OAuth apps id).

And user interface(``Page``) for input username.

**Comment by nuitsjp** [comment]
I tried to modify the model.

* Add User table.  
* Add User table relation.

AuthCategory : Twitter, Facebook, ...

Need some to a different table for each authentication?

![bluemonkeyer](https://cloud.githubusercontent.com/assets/16175660/19582624/2c972ff8-9771-11e6-9d37-f5324973a740.jpg)

**Comment by runceel** [comment]
Azure Mobile apps limitation...
Table data filter behavior use userId column. 
UserId columns set sid direct. sid is string, for example 'sid; xxxxxx'.

And Id, createAt, updateAt, version columns set value automatically. 
Developer can't set value.

Because so, all tables primary key columns shoud rename to id.
And Expense, Report and ExpenseReceipt table have userId columns(This columns set sid text.)
And User table sid columns rename to userId.

つかれた。

**Comment by nuitsjp** [comment]
createAt, updateAt, version is omitted.
It was fixed in the model. 
Please check it.

![image](https://cloud.githubusercontent.com/assets/16175660/19592839/8c9698ac-97b8-11e6-8f0e-5ca9bd64b919.png)

To do with the Department?

**Comment by nuitsjp** [comment]
Updated Model.
Please check it.
![image](https://cloud.githubusercontent.com/assets/16175660/19599221/a309100c-97da-11e6-8737-2fe6e826cbbb.png)

**Comment by runceel** [comment]
I have litte suggestion. CategoryId column of Expense table type is nvarchar(max).

**Comment by nuitsjp** [comment]
It's my mistake.
Fixed.

![image](https://cloud.githubusercontent.com/assets/16175660/19624937/453e9ba6-9945-11e6-978f-451cc20c2d13.png)

**Comment by runceel** [comment]
Thx!! I think that it's ok.
