### ISSUE TITLE
To determine Visual Studio Projects

### ISSUE THREAD

**Issue by nuitsjp** [ProjectBlueMonkey/BlueMonkey#13]
Before begin the implementation, we want to determine Visual Studio Projects.
To do so, I will create a base for discussion.
It creates up to 25 October.

**Comment by nuitsjp** [comment]
I tried to draw a rough sketch.
Please comments and suggestions.

![image](https://cloud.githubusercontent.com/assets/16175660/19639539/e501a010-9a13-11e6-8101-3e272563b74b.png)

**Comment by nuitsjp** [comment]
Created High resolution image.
![bluemonkey-componentmodel](https://cloud.githubusercontent.com/assets/16175660/19668689/7b3d5d6e-9a94-11e6-9ac4-63a1a4b7bbcb.jpg)

**Comment by runceel** [comment]
I agree.
