### ISSUE TITLE
To determine the Unit Test Framework

### ISSUE THREAD

**Issue by nuitsjp** [ProjectBlueMonkey/BlueMonkey#14]
We want to determine before you start the unit test.
I hope the next library.
- xUnit

The reason is as follows.
- To test the INotifyPropertyChanged is easy
- Because using at the Prism
- Because I want to try using

And, I want to use Moq.
It is very useful if you want to create a Mock.

**Comment by runceel** [comment]
vote to xUnit ;)

**Comment by amay077** [comment]
Vote to xUnit.

I have never used to xUnit but I agree @nuitsjp's reasons. :+1:
