### ISSUE TITLE
Update version of Prism to 6.3.0-pre1

### ISSUE THREAD

**Issue by nuitsjp** [ProjectBlueMonkey/BlueMonkey#19]
I would like to apply the update for the following three reasons.

* Hardware/software back button support  
* To use IDestructible  
* Stable's release schedule for the beginning of next year

**Comment by ytabuchi** [comment]
I agree with you. 
How do we decide it ? An amount of +1 ?

**Comment by nuitsjp** [comment]
It's Completed.
