### ISSUE TITLE
How to manage secret keys

### ISSUE THREAD

**Issue by amay077** [ProjectBlueMonkey/BlueMonkey#22]
Some API keys should not contains this repo.
How to manage our secret variables?

My suggestion:

This is simply "using .gitignore" way.

1. Create ``Secrets.cs`` and ``Secrets_sample.cs``
2. Add ``Secrets.cs`` to ``.csproj`` and ``.gitignore``
3. Add ``Secrets_sample.cs`` to repo

``Secrets.cs`` and ``Secrets_sample.cs`` are follows code:

```
// Secrets.cs
public static class Secrets {
  public static readonly string SOME_APIKEY = "adke3jnRDdlED64";  // actual value
}
```

```
// Secrets_sample.cs
public static class Secrets {
  public static readonly string SOME_APIKEY = "your_api_key";  // dummy value
}
```

We should don't add ``Secrets.cs`` to repo. 
Would you like store this in our slack channel?
(``Secrets_sample.cs`` provides usage and hint.)

**Comment by nuitsjp** [comment]
If you do not consider key encryption, I think that it is good.
However, if it is a Stack, it will flow.
Is there a way to manage it well?
Separately, it may be good to share important files with VSTS or OneDrive.

**Comment by ytabuchi** [comment]
In my opinion, the amay-san's way might be good because it is not so important for this project.

**Comment by nuitsjp** [comment]
This approach was adopted.
https://github.com/ProjectBlueMonkey/BlueMonkey/pull/41
