### ISSUE TITLE
Implement client side function Update Expence with test

### ISSUE THREAD

**Issue by nuitsjp** [ProjectBlueMonkey/BlueMonkey#26]
At the title.

**Comment by runceel** [comment]
I found that different between ER diagram and Client side entities.

Expense entity have Name property at client side, But ER diagram doesn't have this column. 

Now, error occur in azure server side.

**Comment by nuitsjp** [comment]
I didn't think anything because it was from the beginning...
I have a new issue.

**Comment by nuitsjp** [comment]
Remove the Name property from expense #60
