### ISSUE TITLE
Modify code formatting rule

### ISSUE THREAD

**Issue by ayasesh** [ProjectBlueMonkey/BlueMonkey#7]
My policy is avoiding new line.
I hope I can set the template for avoiding new lines.

```
if (hoge != null) {
}
```

👍

**Comment by runceel** [comment]
I like this.

```
if (xxx)
{
}

foreach (var x in items)
{
}
```

It is default Visual Studio formatting rule.

**Comment by amay077** [comment]
I like Visual Studio formatting style too. 👍 

And I **should not** escape brace.

😱 

```
if (isHoge)
    GotoFail();
    GoToFail();
```

😃 

```
if (isHoge)
{
    GotoFail();
}
GoToFail();
```

**Comment by amay077** [comment]
How about .NET Naming and directory making policies?

I like this.

![2016-10-19 18 47 13](https://cloud.githubusercontent.com/assets/401369/19513915/a71de910-962c-11e6-82d6-15b974c6d5bf.png)

**Comment by runceel** [comment]
Visual Studio default rule is Hierarchical.

**Comment by ayasesh** [comment]
Oh...

Thanks for going through this.
